select LEFT(ISNULL(ef.DrugShort1, ''), 16) as DrugName, '' as Dose, '0' as Quantity, '' as Freq, '' as Form, '-1' as Status, ISNULL(ef.VisitDate, '1900-01-01') as Da, '' as Reason, '' as Remark, LEFT(CAST(ISNULL(ef.ExpFollowUpID, ABS(CHECKSUM(NEWID()))) AS VARCHAR(17)), 17) as Vid from tblExposeFollowUp ef left outer join tblCodeID ci on ci.PtCode=ef.ptcode and ci.ClinicId like 'E%' where ef.DrugShort1 is not null and ci.ClinicID is not null
UNION ALL
select LEFT(ISNULL(ef.DrugShort2, ''), 16) as DrugName, '' as Dose, '0' as Quantity, '' as Freq, '' as Form, '-1' as Status, ISNULL(ef.VisitDate, '1900-01-01') as Da, '' as Reason, '' as Remark, LEFT(CAST(ISNULL(ef.ExpFollowUpID, ABS(CHECKSUM(NEWID()))) AS VARCHAR(17)), 17) as Vid from tblExposeFollowUp ef left outer join tblCodeID ci on ci.PtCode=ef.ptcode and ci.ClinicId like 'E%' where ef.DrugShort2 is not null and ci.ClinicID is not null
UNION ALL
select LEFT(ISNULL(ef.DrugShort3, ''), 16) as DrugName, '' as Dose, '0' as Quantity, '' as Freq, '' as Form, '-1' as Status, ISNULL(ef.VisitDate, '1900-01-01') as Da, '' as Reason, '' as Remark, LEFT(CAST(ISNULL(ef.ExpFollowUpID, ABS(CHECKSUM(NEWID()))) AS VARCHAR(17)), 17) as Vid from tblExposeFollowUp ef left outer join tblCodeID ci on ci.PtCode=ef.ptcode and ci.ClinicId like 'E%' where ef.DrugShort3 is not null and ci.ClinicID is not null
UNION ALL
select LEFT(ISNULL(ef.DrugShort4, ''), 16) as DrugName, '' as Dose, '0' as Quantity, '' as Freq, '' as Form, '-1' as Status, ISNULL(ef.VisitDate, '1900-01-01') as Da, '' as Reason, '' as Remark, LEFT(CAST(ISNULL(ef.ExpFollowUpID, ABS(CHECKSUM(NEWID()))) AS VARCHAR(17)), 17) as Vid from tblExposeFollowUp ef left outer join tblCodeID ci on ci.PtCode=ef.ptcode and ci.ClinicId like 'E%' where ef.DrugShort4 is not null and ci.ClinicID is not null
UNION ALL
select LEFT(ISNULL(ef.DrugShort5, ''), 16) as DrugName, '' as Dose, '0' as Quantity, '' as Freq, '' as Form, '-1' as Status, ISNULL(ef.VisitDate, '1900-01-01') as Da, '' as Reason, '' as Remark, LEFT(CAST(ISNULL(ef.ExpFollowUpID, ABS(CHECKSUM(NEWID()))) AS VARCHAR(17)), 17) as Vid from tblExposeFollowUp ef left outer join tblCodeID ci on ci.PtCode=ef.ptcode and ci.ClinicId like 'E%' where ef.DrugShort5 is not null and ci.ClinicID is not null
